### ISSUE TITLE
Multiple popup windows

### ISSUE THREAD

**Issue by nightrider77** [gasparesganga/jquery-popup-window#11]
If I open popup, then minimize or collapse it, popupwindow_overlay of this popup is still visible and continues to block everything under it. So what's the purpose of minimizing/collapsing popup? Anyway you can't operate with 2 or more popups at the same time...

**Comment by gasparesganga** [comment]
Yeah, it is so bad, of course no one tested it for this basic behaviour before releasing it, unbelievable!!!

You can read the official documentation page or maybe provide some specific code where you are experiencing those issues... or maybe take for granted that you _can't operate with 2 or more popups at the same time..._ 
Meh!

**Comment by nightrider77** [comment]
Sorry, I misunderstood the "modal" meaning in config.
