### ISSUE TITLE
Few questions: Dimensions issue and on close event 

### ISSUE THREAD

**Issue by nightrider77** [gasparesganga/jquery-popup-window#12]
Hello.

1. It will be good to add a simple checking of maximum window size to the code, to avoid oversize of popup, something like this:

To defaults:
`maxHeight: window.innerHeight,`
`maxWidth: window.innerWidth,`

To _Init function:

`if ( settings.height > settings.maxHeight ) settings.height = settings.maxHeight;`
`if ( settings.width > settings.maxWidth ) settings.width = settings.maxHeight;`

In fact, it's good to make it a little bit responsive, so width and height can have 'auto' values and will be recalculated on-the-fly, depending on popup content changing.

2. It will be good to be able to interrupt closing of popup.

`$("#example1").PopupWindow({`
`    title   : "Example 1 - Complete playground",`
`    modal   : false,`
`    onClose: (e) => {`
`      if ( someVariable ) {`
`       e.close(); // popup will close if some condition is true, useful even for async functions`
`      } else {`
`       e.interrupt(); // popup won't close [optional, if needed by popup code]`
`      }`
`    }`
`});`

I think _$(selector).on("*", handler)_ coding style is a little bit outdated and doesn't contribute to well structuring of code.
It's comfortable when all the code, related to this popup, will be in a one place.

**Comment by nightrider77** [comment]
Regarding the second question, something like this:

To defaults:
`onClose: null,`

Replace _Close function with:

`    function _Close(popupWindow){`
`        if (!_CheckPopupWindow(popupWindow) || !popupWindow.data("opened")) return;`
`        var settings = popupWindow.data("settings");`
`        if ( "onClose" in settings && typeof settings.onClose == 'function' ) `
`            settings.onClose({ close:()=>{ _CloseFinal(popupWindow) } });`
`                 else _CloseFinal(popupWindow);`
`    }`
` `
`    function _CloseFinal(popupWindow){`
`        if (!_CheckPopupWindow(popupWindow) || !popupWindow.data("opened")) return;`
`        if (popupWindow.data("minimized")) _Unminimize(popupWindow);`
`        popupWindow.data("overlay").hide();`
`        popupWindow.data("opened", false);`
`        _TriggerEvent(popupWindow, "close");`
`    }`

**Comment by gasparesganga** [comment]
Thank you for your feedback.
Unfortunately, I do not have much time to maintain and improve this plugin anymore.
Other users had given me great ideas but my work and personal schedule is very strict.

Feel free to fork it and develop the way you prefer. Provided you remember to mention somewhere in the credits/license that your plugin is based on the original version by me, I would definitely encourage that! ;)

If you decide to pursue this route and want to publish some documentation on some website of yours, let me know (maybe by email) and I can send you the source Markdown file I used to generate to official documentation page on my website, no problem.

**Comment by nightrider77** [comment]
Thanks for your reply!
But the architecture and style of the code are already outdated, it's easier to rewrite it all from scratch...
