### ISSUE TITLE
how to show popup  to right position

### ISSUE THREAD

**Issue by deawx** [gasparesganga/jquery-popup-window#2]
how to config  for popup  show  right position ?

thank you for excellent popup plugin.

**Comment by gasparesganga** [comment]
Are you looking for the [top](https://gasparesganga.com/labs/jquery-popup-window/#top) and [left](https://gasparesganga.com/labs/jquery-popup-window/#left) options, or you mean something else?
In case you wanted to express the position *from the right*, you can make ethe math using your viewport width and the PopupWindow width.
